#!/bin/bash
my bin bash my mom is always is good. my dad is also super best.
my bin bash my mom is always is good. my dad is also super best.
my bin bash my mom is always is good. my dad is also super best.

